name: Build
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile
        uses: xu-cheng/latex-action@v3
        with:
          root_file: abstract.tex
      - name: Gather artifacts
        run: |
          mkdir -p public
          mv *.log public/
          mv *.pdf public/
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          path: public
